name: CI (OSS)

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      saas: false
      include_mysql: ${{ github.ref_name != 'self-hosted' }}
